# Generated by Django 2.0.6 on 2018-09-03 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20180826_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='masked_key',
        ),
    ]
